/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LevelRouteImport } from './routes/level'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as SendRouteImport } from './routes/send'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as AdminSubmissionsIndexRouteImport } from './routes/admin.submissions.index'
import { Route as AdminSubmissionsSubmissionIdRouteImport } from './routes/admin.submissions.$submissionId'
import { Route as AdminTasksIndexRouteImport } from './routes/admin.tasks.index'
import { Route as AdminTasksTaskIdRouteImport } from './routes/admin.tasks.$taskId'
import { Route as AdminTasksNewRouteImport } from './routes/admin.tasks.new'
import { Route as AdminWithdrawalsIndexRouteImport } from './routes/admin.withdrawals.index'
import { Route as AdminWithdrawalsWithdrawalIdRouteImport } from './routes/admin.withdrawals.$withdrawalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelRoute = LevelRouteImport.update({
  id: '/level',
  path: '/level',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const AdminSubmissionsIndexRoute = AdminSubmissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSubmissionsRoute,
} as any)
const AdminSubmissionsSubmissionIdRoute =
  AdminSubmissionsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => AdminSubmissionsRoute,
  } as any)
const AdminTasksIndexRoute = AdminTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTasksRoute,
} as any)
const AdminTasksTaskIdRoute = AdminTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AdminTasksRoute,
} as any)
const AdminTasksNewRoute = AdminTasksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTasksRoute,
} as any)
const AdminWithdrawalsIndexRoute = AdminWithdrawalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWithdrawalsRoute,
} as any)
const AdminWithdrawalsWithdrawalIdRoute =
  AdminWithdrawalsWithdrawalIdRouteImport.update({
    id: '/$withdrawalId',
    path: '/$withdrawalId',
    getParentRoute: () => AdminWithdrawalsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/history': typeof HistoryRoute
  '/level': typeof LevelRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/send': typeof SendRoute
  '/tasks': typeof TasksRouteWithChildren
  '/withdraw': typeof WithdrawRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/submissions': typeof AdminSubmissionsRouteWithChildren
  '/admin/tasks': typeof AdminTasksRouteWithChildren
  '/admin/withdrawals': typeof AdminWithdrawalsRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/admin/': typeof AdminIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/admin/submissions/$submissionId': typeof AdminSubmissionsSubmissionIdRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/withdrawals/$withdrawalId': typeof AdminWithdrawalsWithdrawalIdRoute
  '/admin/submissions/': typeof AdminSubmissionsIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/withdrawals/': typeof AdminWithdrawalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/level': typeof LevelRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/send': typeof SendRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/login': typeof AdminLoginRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/admin': typeof AdminIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/admin/submissions/$submissionId': typeof AdminSubmissionsSubmissionIdRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/withdrawals/$withdrawalId': typeof AdminWithdrawalsWithdrawalIdRoute
  '/admin/submissions': typeof AdminSubmissionsIndexRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/admin/withdrawals': typeof AdminWithdrawalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/history': typeof HistoryRoute
  '/level': typeof LevelRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/send': typeof SendRoute
  '/tasks': typeof TasksRouteWithChildren
  '/withdraw': typeof WithdrawRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/submissions': typeof AdminSubmissionsRouteWithChildren
  '/admin/tasks': typeof AdminTasksRouteWithChildren
  '/admin/withdrawals': typeof AdminWithdrawalsRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/admin/': typeof AdminIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/admin/submissions/$submissionId': typeof AdminSubmissionsSubmissionIdRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/withdrawals/$withdrawalId': typeof AdminWithdrawalsWithdrawalIdRoute
  '/admin/submissions/': typeof AdminSubmissionsIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/withdrawals/': typeof AdminWithdrawalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/history'
    | '/level'
    | '/profile'
    | '/referral'
    | '/send'
    | '/tasks'
    | '/withdraw'
    | '/admin/login'
    | '/admin/submissions'
    | '/admin/tasks'
    | '/admin/withdrawals'
    | '/tasks/$taskId'
    | '/admin/'
    | '/tasks/'
    | '/admin/submissions/$submissionId'
    | '/admin/tasks/$taskId'
    | '/admin/tasks/new'
    | '/admin/withdrawals/$withdrawalId'
    | '/admin/submissions/'
    | '/admin/tasks/'
    | '/admin/withdrawals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/level'
    | '/profile'
    | '/referral'
    | '/send'
    | '/withdraw'
    | '/admin/login'
    | '/tasks/$taskId'
    | '/admin'
    | '/tasks'
    | '/admin/submissions/$submissionId'
    | '/admin/tasks/$taskId'
    | '/admin/tasks/new'
    | '/admin/withdrawals/$withdrawalId'
    | '/admin/submissions'
    | '/admin/tasks'
    | '/admin/withdrawals'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/history'
    | '/level'
    | '/profile'
    | '/referral'
    | '/send'
    | '/tasks'
    | '/withdraw'
    | '/admin/login'
    | '/admin/submissions'
    | '/admin/tasks'
    | '/admin/withdrawals'
    | '/tasks/$taskId'
    | '/admin/'
    | '/tasks/'
    | '/admin/submissions/$submissionId'
    | '/admin/tasks/$taskId'
    | '/admin/tasks/new'
    | '/admin/withdrawals/$withdrawalId'
    | '/admin/submissions/'
    | '/admin/tasks/'
    | '/admin/withdrawals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  LevelRoute: typeof LevelRoute
  ProfileRoute: typeof ProfileRoute
  ReferralRoute: typeof ReferralRoute
  SendRoute: typeof SendRoute
  TasksRoute: typeof TasksRouteWithChildren
  WithdrawRoute: typeof WithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level': {
      id: '/level'
      path: '/level'
      fullPath: '/level'
      preLoaderRoute: typeof LevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/admin/submissions/': {
      id: '/admin/submissions/'
      path: '/'
      fullPath: '/admin/submissions/'
      preLoaderRoute: typeof AdminSubmissionsIndexRouteImport
      parentRoute: typeof AdminSubmissionsRoute
    }
    '/admin/submissions/$submissionId': {
      id: '/admin/submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/admin/submissions/$submissionId'
      preLoaderRoute: typeof AdminSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AdminSubmissionsRoute
    }
    '/admin/tasks/': {
      id: '/admin/tasks/'
      path: '/'
      fullPath: '/admin/tasks/'
      preLoaderRoute: typeof AdminTasksIndexRouteImport
      parentRoute: typeof AdminTasksRoute
    }
    '/admin/tasks/$taskId': {
      id: '/admin/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/admin/tasks/$taskId'
      preLoaderRoute: typeof AdminTasksTaskIdRouteImport
      parentRoute: typeof AdminTasksRoute
    }
    '/admin/tasks/new': {
      id: '/admin/tasks/new'
      path: '/new'
      fullPath: '/admin/tasks/new'
      preLoaderRoute: typeof AdminTasksNewRouteImport
      parentRoute: typeof AdminTasksRoute
    }
    '/admin/withdrawals/': {
      id: '/admin/withdrawals/'
      path: '/'
      fullPath: '/admin/withdrawals/'
      preLoaderRoute: typeof AdminWithdrawalsIndexRouteImport
      parentRoute: typeof AdminWithdrawalsRoute
    }
    '/admin/withdrawals/$withdrawalId': {
      id: '/admin/withdrawals/$withdrawalId'
      path: '/$withdrawalId'
      fullPath: '/admin/withdrawals/$withdrawalId'
      preLoaderRoute: typeof AdminWithdrawalsWithdrawalIdRouteImport
      parentRoute: typeof AdminWithdrawalsRoute
    }
  }
}

interface AdminSubmissionsRouteChildren {
  AdminSubmissionsSubmissionIdRoute: typeof AdminSubmissionsSubmissionIdRoute
  AdminSubmissionsIndexRoute: typeof AdminSubmissionsIndexRoute
}

const AdminSubmissionsRouteChildren: AdminSubmissionsRouteChildren = {
  AdminSubmissionsSubmissionIdRoute: AdminSubmissionsSubmissionIdRoute,
  AdminSubmissionsIndexRoute: AdminSubmissionsIndexRoute,
}

const AdminSubmissionsRouteWithChildren =
  AdminSubmissionsRoute._addFileChildren(AdminSubmissionsRouteChildren)

interface AdminTasksRouteChildren {
  AdminTasksTaskIdRoute: typeof AdminTasksTaskIdRoute
  AdminTasksNewRoute: typeof AdminTasksNewRoute
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute
}

const AdminTasksRouteChildren: AdminTasksRouteChildren = {
  AdminTasksTaskIdRoute: AdminTasksTaskIdRoute,
  AdminTasksNewRoute: AdminTasksNewRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
}

const AdminTasksRouteWithChildren = AdminTasksRoute._addFileChildren(
  AdminTasksRouteChildren,
)

interface AdminWithdrawalsRouteChildren {
  AdminWithdrawalsWithdrawalIdRoute: typeof AdminWithdrawalsWithdrawalIdRoute
  AdminWithdrawalsIndexRoute: typeof AdminWithdrawalsIndexRoute
}

const AdminWithdrawalsRouteChildren: AdminWithdrawalsRouteChildren = {
  AdminWithdrawalsWithdrawalIdRoute: AdminWithdrawalsWithdrawalIdRoute,
  AdminWithdrawalsIndexRoute: AdminWithdrawalsIndexRoute,
}

const AdminWithdrawalsRouteWithChildren =
  AdminWithdrawalsRoute._addFileChildren(AdminWithdrawalsRouteChildren)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRouteWithChildren
  AdminTasksRoute: typeof AdminTasksRouteWithChildren
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminSubmissionsRoute: AdminSubmissionsRouteWithChildren,
  AdminTasksRoute: AdminTasksRouteWithChildren,
  AdminWithdrawalsRoute: AdminWithdrawalsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HistoryRoute: HistoryRoute,
  LevelRoute: LevelRoute,
  ProfileRoute: ProfileRoute,
  ReferralRoute: ReferralRoute,
  SendRoute: SendRoute,
  TasksRoute: TasksRouteWithChildren,
  WithdrawRoute: WithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
